In [3]:
import math

### Scalars, Vectors, Matrices and Tensors

- __Scalars__ A scalar is just a single number. Ex: 1, $\pi$, $\frac{7}{22}$, $e$. In python integers and floats are scalars.

In [6]:
a = 3.5

b = math.pi

print(a,b, type(a), type(b))

3.5 3.141592653589793 <class 'float'> <class 'float'>


In [7]:
a.shape

AttributeError: 'float' object has no attribute 'shape'

- __Vectors__: A vector is an array of numbers. In python we can consider numpy ndarray's as the representatives of the vectors. Possible notations for the vectors: bold letters $\textbf{X}, \textbf{x}$, with an arrow $\vec{X}, \vec{x}$ or just $V, v$ when it is clear from the context that these are vectors.

In [15]:
import numpy as np

x = np.array([11, 2, 5])


## note the shape is just (3,)
## we will see that this is different than (3,1)

print("Type of x is ndarray: ", type(x), "\nx is a ndarray: ", x,
      "\nnumpy array has shape attribute:" , x.shape)

Type of x is ndarray:  <class 'numpy.ndarray'> 
x is a ndarray:  [11  2  5] 
numpy array has shape attribute: (3,)


In [23]:
## note that vectors has indices or coefficients:

x_1 = x[0]

x_2 = x[1]

x_3 = x[2]

print(
"""First index is: {} 
The second index is: {} 
the third index is: {}""".format(x_1,x_2, x_3)
)

First index is: 11 
The second index is: 2 
the third index is: 5


- __Matrices__ A matrix is a 2D array of numbers: Again we will use ndarrays for matrices.


In [28]:
A = np.array([[1,2,3], [11,5,7], [13,17,19], [1,0,2]])
print(
"""
A is a matrix: 
{}
The shape of A is:
{}
The type of A is: 
{}
""".format(A, A.shape, type(A)))
    


A is a matrix: 
[[ 1  2  3]
 [11  5  7]
 [13 17 19]
 [ 1  0  2]]
The shape of A is:
(4, 3)
The type of A is: 
<class 'numpy.ndarray'>



In [5]:
## note that we can access the entries within a matrix with the indices too.
## Also note that python starts counting from 0
print(A[0,1], A[0, 2], A[2, 2])

2 3 19


In [29]:
A

array([[ 1,  2,  3],
       [11,  5,  7],
       [13, 17, 19],
       [ 1,  0,  2]])

__Your Turn__

- Find the number at the second column and the third row

- Find all the elements in the first column and keep it as a 1D array

In [49]:
l = [2,3,4,5]
array_l= np.array(l)

array_l

array([2, 3, 4, 5])

Note that numpy is really handy in terms of basic operations.

In [37]:
## Recall x is an 1D ndarray: 
## This can be a row of a dataset or residual errors

x

array([11,  2,  5])

In [74]:
## there are built-in methods we can use easily.
print("x is:",x )
print("y is:", y)

print(x.mean())
## find the mean of numbers in y
print(x.std())
#find the mean of numbers in y
print(x.var())
# find the variance of numbers in y
print("x:", x)

## we can multiply vectors with scalars
print("5 times x:", 5*x)
## we can multiply vector with each other:
print("x times x:", x*x)
## We can add and subtract vectors
print("y-x:", y - x)

x is: [3 7 4]
y is: [2 0 5]
4.666666666666667
1.699673171197595
2.888888888888889
x: [3 7 4]
5 times x: [15 35 20]
x times x: [ 9 49 16]
y-x: [-1 -7  1]


In addition to item by item multiplication we have another way of 
multiplying vectors and matrices. This is called dot product.

In [76]:
print("The dot product of x with itself:", x.dot(x))

The dot product of x with itself: 74


In [77]:
print("The dot product of x with y:", x.dot(y))

The dot product of x with y: 26


Now find the dot product of y with x:

In [78]:
## your code is here

In [81]:
## note that we cannot dot product two different shape vectors
u = np.array([0,-1, 5,7])
#x.dot(u)
# u.dot(x)

In [6]:
## We can also access a row in a matrix

print('The second row of A: ', A[1,: ],'\nThe third row of A: ', A[2, :])


## We can also access the columns

print('The second column of A: ', A[:,1],'\nThe third column of A: ', A[:,2])


The second row of A:  [11  5  7] 
The third row of A:  [13 17 19]
The second column of A:  [ 2  5 17  0] 
The third column of A:  [ 3  7 19  2]


In [90]:
a = np.array([1,2,3])


## From a (3,) dimensional array we can create
## column and row vectors in different ways
new_a = a[np.newaxis, :]
print(new_a.shape)

new_a = a[:, np.newaxis]
new_a.shape

(1, 3)


(3, 1)

- __Tensors__ An array of numbers arranged on a regular grid with a variable number of axis is known as a tensor. We can create tensors with numpy but there will be other libraries also that is using tensors. 

In [8]:
## Properties of the tensors will not be discussed in this notebook

T = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]
             ])
T.shape

(3, 3, 3)

## Multiplying Vectors and Matrices

In [30]:
B = np.array([[1,0], 
              [1,2], 
              [0,2]
             ])
display(A, B, A.dot(B))

display(A.shape, B.shape, A.dot(B).shape)

array([[ 1,  2,  3],
       [11,  5,  7],
       [13, 17, 19],
       [ 1,  0,  2]])

array([[1, 0],
       [1, 2],
       [0, 2]])

array([[ 3, 10],
       [16, 24],
       [30, 72],
       [ 1,  4]])

(4, 3)

(3, 2)

(4, 2)

In [31]:
B.shape

(3, 2)

In [32]:
A.shape

(4, 3)

In [37]:
## we can use 'dot' product to multiply two vectors.
## here a, b are of shape (3,)
## Note that the result will be a scalar

a = np.array([1,2,3])
b = np.array([1,0,1])

a.dot(b)

4

In [40]:
## If the vectors have shape (1,3) then this method would not work

a = np.array([[1,2,3]])

b = np.array([[1,0,1]])

a.T.dot(b)

array([[1, 0, 1],
       [2, 0, 2],
       [3, 0, 3]])

In [13]:
## instead we can use transpose first and then dot

## here a is of shape (1,3) and b.transpose is of shape (3,1)
## so the result will be of shape (1,1)

print(a.dot(b.transpose()),a.dot(b.transpose()).shape )

[[4]] (1, 1)


In [14]:
## If we take first a.transpose what do we get?

print(a.transpose().dot(b),a.transpose().dot(b).shape )

[[1 0 1]
 [2 0 2]
 [3 0 3]] (3, 3)


In [44]:
## we can use np.linalg module to do some linear algebra
## for example let's use np.linalg.inv for taking inverse of a matrix

A = np.array([[1,2,3], [1,0,13], [0,2,1]])

np.linalg.inv(A)

array([[ 1.18181818, -0.18181818, -1.18181818],
       [ 0.04545455, -0.04545455,  0.45454545],
       [-0.09090909,  0.09090909,  0.09090909]])

In [48]:
## note that not all matrices are invertible
## np.linalg.inv gives an error when we try to 
## invert a non-invertible matrix
A = np.array([[1,2,3], [1,0,2], [0,2,1]])

np.linalg.inv(A)



LinAlgError: Singular matrix

In [17]:
## There is also .eig method that allow
## allow us to find eigenvalues and eigenvectors
## note that the matrix should be a square matrix

eig_val, eig_vec = np.linalg.eig(A)

display(eig_val, eig_vec)

array([-1.44948974e+00,  3.05311332e-16,  3.44948974e+00])

array([[-0.14072662,  0.87287156,  0.81511137],
       [-0.76688827,  0.21821789,  0.44872717],
       [ 0.62616165, -0.43643578,  0.3663842 ]])

In [18]:
## Two things returned from np.linalg.eig 
## 1: an array of shape (n, ) for the eigenvalues
## 2: an array of shape (n,n) for eigenvectors as columns

c = eig_val[0]*eig_vec[:,0]

d = A.dot(eig_vec[:,0])

display(c,d)

array([ 0.20398179,  1.11159667, -0.90761488])

array([ 0.20398179,  1.11159667, -0.90761488])

Now we can see how to use matrix algrebra to solve least square problem.

In [49]:
import pandas as pd

import numpy as np

In [50]:
df = pd.read_csv('data/Income1.csv', index_col = 0)

In [51]:
df.head()

Education     Income
1  10.000000  26.658839
2  10.401338  27.306435
3  10.842809  22.132410
4  11.244147  21.169841
5  11.645485  15.192634

In [52]:
df['intercept'] = np.zeros(len(df))

In [53]:
df['intercept'] = 1

In [60]:
X = df[['Education', 'intercept']].values

y = df['Income'].values

One (who?) can show that the solution $\beta$ to the least square regression given as: 

$$ \beta = (X^{\top}X)^{-1}X^{\top}y$$

(I know this is a little bit hard to buy but you can check [Wikipedia-Linear Regression](https://en.wikipedia.org/wiki/Linear_regression))

In [61]:
X_tr_X_inv = np.linalg.inv(X.transpose().dot(X))

In [62]:
X_tr_X_inv.dot(X.transpose()).dot(y)

array([  5.59948287, -39.44625668])

In [55]:
from sklearn.linear_model import LinearRegression

In [56]:
X  = df.Education.values.reshape(-1,1)
lr = LinearRegression()

lr.fit(X,y)



LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [57]:
print(lr.coef_, lr.intercept_)

[5.59948287] -39.446256679096194


In [65]:
A*A

array([[1, 4, 9],
       [1, 0, 4],
       [0, 4, 1]])

In [66]:
A

array([[1, 2, 3],
       [1, 0, 2],
       [0, 2, 1]])

## Extra Sources

[Penn State Matrix Algebra Review](https://newonlinecourses.science.psu.edu/statprogram/reviews/matrix-algebra)

[IBM's matrix algebra class](https://cognitiveclass.ai/blog/nested-lists-multidimensional-numpy-arrays)