In [136]:
from sympy import *
import math

### Scalars, Vectors, Matrices and Tensors

- __Scalars__ A scalar is just a single number. Ex: 1, $\pi$, $\frac{7}{22}$, $e$. In python integers and floats are scalars.

In [137]:
a = 3

b = math.pi

print(a,b, type(a), type(b))

3 3.141592653589793 <class 'int'> <class 'float'>


- __Vectors__: A vector is an array of numbers. In python we can consider numpy ndarray's as the representatives of the vectors. Possible notations for the vectors: bold letters $\textbf{X}, \textbf{x}$, with an arrow $\vec{X}, \vec{x}$ or just $V, v$ when it is clear from the context that these are vectors.

In [138]:
import numpy as np

x = np.array([11, math.e, 5])


## note the shape is just (3,)
## we will see that this is different than (3,1)

print(x, x.shape, type(x))

[11.          2.71828183  5.        ] (3,) <class 'numpy.ndarray'>


In [139]:
## note that vectors has indices or coefficients:

x_1 = x[0]

x_2 = x[1]

x_3 = x[2]

print(x_1,x_2,x_3)

11.0 2.718281828459045 5.0


- __Matrices__ A matrix is a 2D array of numbers: Again we will use ndarrays for matrices.


In [140]:
A = np.array([[1,2,3], [11,5,7], [13,17,19], [1,0,2]])
print(A, A.shape, type(A))

[[ 1  2  3]
 [11  5  7]
 [13 17 19]
 [ 1  0  2]] (4, 3) <class 'numpy.ndarray'>


In [141]:
## note that we can access the entries within a matrix with the indices too.
## Also note that python starts counting from 0
print(A[0,1], A[0, 2], A[2, 2])

2 3 19


In [142]:
## We can also access a row in a matrix

print('The second row of A: ', A[1,: ],'\nThe third row of A: ', A[2, :])


## We can also access the columns

print('The second column of A: ', A[:,1],'\nThe third column of A: ', A[:,2])


The second row of A:  [11  5  7] 
The third row of A:  [13 17 19]
The second column of A:  [ 2  5 17  0] 
The third column of A:  [ 3  7 19  2]


In [143]:
a = np.array([1,2,3])


## From a (3,) dimensional array we can create
## column and row vectors in different ways
display(a[np.newaxis, :], a[:, np.newaxis])

## or we can use reshape method
display(a.reshape(3,1), a.reshape(1,3))

## also there is a transpose method available

display(a, a.reshape(1,3), a.reshape(1,3).transpose())

## note that a and a.reshape(1,3) don't have the same structure

display(a.shape, a.reshape(1,3).shape, a.reshape(1,3).transpose().shape)

array([[1, 2, 3]])

array([[1],
       [2],
       [3]])

array([[1],
       [2],
       [3]])

array([[1, 2, 3]])

array([1, 2, 3])

array([[1, 2, 3]])

array([[1],
       [2],
       [3]])

(3,)

(1, 3)

(3, 1)

- __Tensors__ An array of numbers arranged on a regular grid with a variable number of axis is known as a tensor. We can create tensors with numpy but there will be other libraries also that is using tensors. 

In [144]:
## Properties of the tensors will not be discussed in this notebook

T = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]
             ])
T.shape

(3, 3, 3)

## Multiplying Vectors and Matrices

In [145]:
B = np.array([[1,0], 
              [1,2], 
              [0,2]
             ])
display(A, B, A.dot(B))

display(A.shape, B.shape, A.dot(B).shape)

array([[ 1,  2,  3],
       [11,  5,  7],
       [13, 17, 19],
       [ 1,  0,  2]])

array([[1, 0],
       [1, 2],
       [0, 2]])

array([[ 3, 10],
       [16, 24],
       [30, 72],
       [ 1,  4]])

(4, 3)

(3, 2)

(4, 2)

In [146]:
## we can use 'dot' product to multiply two vectors.
## here a, b are of shape (3,)
## Note that the result will be a scalar

a = np.array([1,2,3])
b = np.array([1,0,1])

a.dot(b)

4

In [147]:
## If the vectors have shape (1,3) then this method would not work

a = np.array([[1,2,3]])

b = np.array([[1,0,1]])

a.dot(b)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [148]:
## instead we can use transpose first and then dot

## here a is of shape (1,3) and b.transpose is of shape (3,1)
## so the result will be of shape (1,1)

print(a.dot(b.transpose()),a.dot(b.transpose()).shape )

[[4]] (1, 1)


In [149]:
## If we take first a.transpose what do we get?

print(a.transpose().dot(b),a.transpose().dot(b).shape )

[[1 0 1]
 [2 0 2]
 [3 0 3]] (3, 3)


In [150]:
## we can use np.linalg module to do some linear algebra
## for example let's use np.linalg.inv for taking inverse of a matrix

A = np.array([[1,2,3], [1,0,13], [0,2,1]])

np.linalg.inv(A)

array([[ 1.18181818, -0.18181818, -1.18181818],
       [ 0.04545455, -0.04545455,  0.45454545],
       [-0.09090909,  0.09090909,  0.09090909]])

In [151]:
## note that not all matrices are invertible
## np.linalg.inv gives an error when we try to 
## invert a non-invertible matrix
A = np.array([[1,2,3], [1,0,2], [0,2,1]])

np.linalg.inv(A)

LinAlgError: Singular matrix

In [152]:
## There is also .eig method that allow
## allow us to find eigenvalues and eigenvectors
## note that the matrix should be a square matrix

eig_val, eig_vec = np.linalg.eig(A)

display(eig_val, eig_vec)

array([-1.44948974e+00,  3.05311332e-16,  3.44948974e+00])

array([[-0.14072662,  0.87287156,  0.81511137],
       [-0.76688827,  0.21821789,  0.44872717],
       [ 0.62616165, -0.43643578,  0.3663842 ]])

In [153]:
## Two things returned from np.linalg.eig 
## 1: an array of shape (n, ) for the eigenvalues
## 2: an array of shape (n,n) for eigenvectors as columns

c = eig_val[0]*eig_vec[:,0]

d = A.dot(eig_vec[:,0])

display(c,d)

array([ 0.20398179,  1.11159667, -0.90761488])

array([ 0.20398179,  1.11159667, -0.90761488])

## Extra Sources

[Penn State Matrix Algebra Review](https://newonlinecourses.science.psu.edu/statprogram/reviews/matrix-algebra)

[IBM's matrix algrabe class](https://cognitiveclass.ai/blog/nested-lists-multidimensional-numpy-arrays)